name: Update README

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README with new timestamp
        run: |
          TIMESTAMP=$(($(date +%s) % 1000000000))
          sed -i "s|https://api.vit.codes/currently-listening?timestamp=[0-9]*|https://api.vit.codes/currently-listening?timestamp=${TIMESTAMP}|" README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README with new timestamp"
          git push
